# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
host: 0.0.0.0
title: karancssag.info
email: info@karancssag.info
fbappid: 2274399879508863
fbpages: 313839985887137
description: > # this means to ignore newlines until "baseurl:"
  Karancsság info
keywords: > # this means to ignore newlines until "baseurl:"
  Karancsság, információ, közérdekű, önkormányzat
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://karancssag.info" # the base hostname & protocol for your site
static_url: "https://static.karancssag.info"
excerpt_separator: <!--more-->
comments:
  enable: false
  provider: 'disqus'

# page_gen
page_gen-dirs: false
page_gen:
  - data: 'jobs.results.szecseny.results'
    template: 'job'
    name: 'subPage'
    title: 'title'
    dir: 'allas'
  - data: 'jobs.results.endrefalva.results'
    template: 'job'
    name: 'subPage'
    title: 'title'
    dir: 'allas'
  - data: 'jobs.results.piliny.results'
    template: 'job'
    name: 'subPage'
    title: 'title'
    dir: 'allas'
  - data: 'jobs.results.szalmatercs.results'
    template: 'job'
    name: 'subPage'
    title: 'title'
    dir: 'allas'
  - data: 'jobs.results.karancssag.results'
    template: 'job'
    name: 'subPage'
    title: 'title'
    dir: 'allas'
  - data: 'jobs.results.sagujfalu.results'
    template: 'job'
    name: 'subPage'
    title: 'title'
    dir: 'allas'
  - data: 'jobs.results.kishartyan.results'
    template: 'job'
    name: 'subPage'
    title: 'title'
    dir: 'allas'
  - data: 'jobs.results.salgotarjan.results'
    template: 'job'
    name: 'subPage'
    title: 'title'
    dir: 'allas'

# Build settings
markdown: kramdown
destination: ./build
exclude: ['README.markdown', 'Gemfile.lock', 'Gemfile']
plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-datapage-generator
